### ISSUE TITLE
Problem resuming failed campaign

### ISSUE THREAD

**Issue by EMOziko** [certsocietegenerale/swordphish-awareness#13]
Hi,

I encoutered problem when using Swordphish and was not able to solve it by myself, so i am reporting it here.

After i started my campaign for large number of targets, in the middle of sending emails, Swordphish just stopped to send new ones, so most of the targets did not received emails.

I found that file swordphish_celery_worker.log contains error about this issue:
```

[2019-10-21 07:52:00,933: ERROR/ForkPoolWorker-2] Task Main.tasks.start_campaign[162a590a-8383-4657-ae04-2dc79e69ea31] raised unexpected: SMTPSenderRefused(421, b'4.4.1 Connection timed out', 'REDACTED')

Traceback (most recent call last):

  File "/home/swordphish/.virtualenvs/swordphish/lib/python3.6/site-packages/celery/app/trace.py", line 382, in trace_task

    R = retval = fun(*args, **kwargs)

  File "/home/swordphish/.virtualenvs/swordphish/lib/python3.6/site-packages/celery/app/trace.py", line 641, in __protected_call__

    return self.run(*args, **kwargs)

  File "/home/swordphish/swordphish/Main/tasks.py", line 59, in start_campaign

    campaign.start()

  File "/home/swordphish/swordphish/Main/models.py", line 587, in start

    attachment_content

  File "/home/swordphish/swordphish/Main/models.py", line 547, in __sendemailwithattachment

    email.send(fail_silently=False)

  File "/home/swordphish/.virtualenvs/swordphish/lib/python3.6/site-packages/django/core/mail/message.py", line 294, in send

    return self.get_connection(fail_silently).send_messages([self])

  File "/home/swordphish/.virtualenvs/swordphish/lib/python3.6/site-packages/django/core/mail/backends/smtp.py", line 110, in send_messages

    sent = self._send(message)

  File "/home/swordphish/.virtualenvs/swordphish/lib/python3.6/site-packages/django/core/mail/backends/smtp.py", line 126, in _send

    self.connection.sendmail(from_email, recipients, message.as_bytes(linesep='\r\n'))

  File "/usr/lib/python3.6/smtplib.py", line 867, in sendmail

    raise SMTPSenderRefused(code, resp, from_addr)

smtplib.SMTPSenderRefused: (421, b'4.4.1 Connection timed out', 'REDACTED') 
```

As the error says, Swordphish received 'Connection timed out' from email server and after this, it just stopped to send new emails.

I was noy able to continue sending emails manually. It would be great if that was possible.

Hope someone can fix this issue.

Thank you for creating such a great software!

**Comment by Heat-Miser** [comment]
Hello,

indeed it's not trivial to resume a campaign, it can be done using Django's shell but there is not such feature in the tool.

Have you been able to identify the problem that lead to this timeout ?

I keep this issue open and I'll think about adding such feature.

**Comment by EMOziko** [comment]
No, unfortunately i was not able to determine root cause. probably email
server got 'ddosed'.

If you ll tell me hint to how to resume campaign from django shell, i will
be very happy.

Thank you very much!
